### PR TITLE
Fix compilation errors when PHP is built with `--enable-maintainer-zts`.

### LINKED ISSUE #5: Compilation fails in some environments
See https://travis-ci.org/romainneutron/php-libev/jobs/5485063 for example.

### PR DESCRIPTION
**Pull request by whatthejeff**
This should fix #5.

### CODE REVIEW

**Comment by whatthejeff** [comment]
Seems to build properly with the travis config from #6: https://travis-ci.org/whatthejeff/php-libev

**Comment by igorw** [comment]
Status?

**Comment by whatthejeff** [comment]
Bump :)

**Comment by whatthejeff** [comment]
Bump :P

**Comment by cboden** [comment]
Bumpin' :musical_note:

**Comment by whatthejeff** [comment]
:+1:

**Comment by igorw** [comment]
hey @m4rw3r, what's the status on this?

**Pull request merged**
